# Docker Compose configuration for DigitalOcean deployment with HTTPS
---
services:
  clwdb:
    image: postgres:17-alpine3.22
    container_name: clwdb
    restart: unless-stopped
    volumes:
      - db-data:/var/lib/postgresql/data
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - edge

  clwapi:
    build:
      context: ./clwapi
      dockerfile: Dockerfile
    container_name: clwapi
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "8001:8001"
    volumes:
      - ./clwapi:/clwapi
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      clwdb:
        condition: service_healthy
    networks:
      - edge
    command: sh -c "pip install -r requirements.txt && uvicorn main:app --host 0.0.0.0 --port 8001 --reload"

networks:
  edge:
    driver: bridge

volumes:
  db-data:
  node_modules:
